# - platform: template
#   sensors:
#     bathroom_humidity_high:
#       friendly_name: "Bathroom Fan On"
#       value_template: >-
#           {{  states('sensor.0x00158d000227b177_humidity')|float >  states('sensor.0x00158d0002c8bafb_humidity')|float + 20 }}

# - platform: trend
#   sensors:
#     bathroom_humidity_high:
#       friendly_name: "Bathroom Fan On"
#       entity_id: sensor.0x00158d000227b177_humidity
#       min_gradient: 0.005
#       device_class: moisture          


- platform: ping
  name: router ping
  host: 192.168.0.1
  count: 5
  scan_interval: 10
  
# - platform: ping
#   name: internet ping
#   host: 8.8.8.8
#   count: 2
#   scan_interval: 60

- platform: mqtt
  name: "PC - Connected"
  state_topic: "iotlink/workgroup/lambot-pc/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1
  
- platform: mqtt
  name: "PC - Media Playing"
  state_topic: "iotlink/workgroup/lambot-pc/windows-monitor/stats/media/playing"
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/lambot-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  payload_on: "True"
  payload_off: "False"
  qos: 1

- platform: mqtt
  name: "PC - Media Muted"
  state_topic: "iotlink/workgroup/lambot-pc/windows-monitor/stats/media/muted"
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/lambot-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  payload_on: "True"
  payload_off: "False"
  qos: 1
  
# Stereo Remote
- platform: mqtt
  name: 'Dining Room Pause'
  state_topic: 'home/stereopower'
  off_delay: 1
  
- platform: mqtt
  name: 'Dining Room Vol 100'
  state_topic: 'home/stereo100'
  off_delay: 1
  
- platform: mqtt
  name: 'Dining Room Vol 50'
  state_topic: 'home/stereo50'
  off_delay: 1
  
- platform: mqtt
  name: 'Dining Room Vol 25'
  state_topic: 'home/stereo25'
  off_delay: 1
  
- platform: mqtt
  name: 'Dining Room Light'
  state_topic: 'home/stereolight'
  off_delay: 1
  
- platform: mqtt
  name: 'Dining Room Brightp'
  state_topic: 'home/stereobrightp'
  off_delay: 1
  
- platform: mqtt
  name: 'Dining Room Brightm'
  state_topic: 'home/stereobrightm'
  off_delay: 1
  
- platform: mqtt
  name: 'Dining Room Modep'
  state_topic: 'home/stereomodep'
  off_delay: 1
  
- platform: mqtt
  name: 'Dining Room Modem'
  state_topic: 'home/stereomodem'
  off_delay: 1
      
- platform: mqtt
  name: 'Dining Room Speedp'
  state_topic: 'home/stereospeedp'
  off_delay: 1
  
- platform: mqtt
  name: 'Dining Room Speedm'
  state_topic: 'home/stereospeedm'
  off_delay: 1

  
  
  
  
  