### sensors/mqtt.yaml ########################################

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless

- platform: mqtt
  name: Zigbee2mqtt Networkmap
  # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
  state_topic: zigbee2mqtt/bridge/networkmap/raw
  value_template: >-
    {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
  # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
  json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw
  
- platform: mqtt
  name: "PC - Current User"
  state_topic: "iotlink/workgroup/lambot-pc/windows-monitor/stats/current-user"
  unit_of_measurement: ''
  icon: mdi:account
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/my-computer/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "PC - Media Volume"
  state_topic: "iotlink/workgroup/lambot-pc/windows-monitor/stats/media/volume"
  unit_of_measurement: '%'
  icon: mdi:speedometer
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/lambot-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
