#### automations/appliance_doorbell.yaml #########################################

- alias: "Doorbell Trigger On"
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000200d63a_contact
      #entity_id: binary_sensor.doorbell_contact
      to: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.doorbell

- alias: "Doorbell Trigger Off"
  trigger:
    - platform: state
      entity_id: input_boolean.doorbell
      to: 'on'
      for:
        seconds: 30
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.doorbell

- alias: "Doorbell Tasker"
  trigger:
    - platform: state
      entity_id: input_boolean.doorbell
      to: 'on'
  condition:
    condition: state
    entity_id: group.presence_motion_no_doorbell
    state: 'off'      
  action:   
    - service: script.notify_home
      data_template:
        message: "AAPPHASS=:=door=:=Doorbell=:=Hello there is someone at the Door"
        
- alias: "Doorbell Tasker Dismiss"
  trigger:
    - platform: state
      entity_id:  binary_sensor.0x00158d0002e2c145_contact
      to: 'on'
  action:   
    - service: script.notify_home
      data_template:
        message: "AAPPHASS=:=door=:=DISMISS"        