#### automations/media_diningroom.yaml #########################################
- alias: "Back Bedroom Stereo On Media playing"
  trigger:
    - platform: state
      entity_id: media_player.back_bedroom
      to: 'playing'
  action:
    - service: switch.turn_on
      entity_id: switch.backbedroomstereo

- alias: "Back Bedroom Stereo Off Media Idle"
  trigger:
    - platform: state
      entity_id: media_player.back_bedroom
      to: 'idle'
      for:
        minutes: 5
    - platform: state
      entity_id: media_player.back_bedroom
      to: 'off'
      for:
        minutes: 2
    - platform: state
      entity_id: media_player.back_bedroom
      to: 'paused'
      for:
        minutes: 75
  action:
    - service: switch.turn_off
      entity_id: switch.backbedroomstereo
    # - service: media_player.volume_set
    #   data_template:
    #     entity_id: media_player.back_bedroom
    #     volume_level: "{{ states('input_number.vol_diningroom') }}"
    - service: media_player.turn_off
      data:
        entity_id: media_player.back_bedroom